# Generated by Django 4.1 on 2022-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='None', null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='No title', max_length=30),
        ),
    ]
