# Generated by Django 4.1 on 2023-01-17 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_genre_profile_bio_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
