# Generated by Django 4.1 on 2023-02-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
