# Generated by Django 4.1 on 2023-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_img',
            field=models.ImageField(null=True, upload_to='genre_img'),
        ),
    ]
