# Generated by Django 4.1 on 2023-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_genre_genre_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='post',
            name='text_body',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
