# Generated by Django 4.1 on 2023-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_followers_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
