# Generated by Django 4.1 on 2023-03-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='no_likes',
        ),
    ]
