# Generated by Django 4.1 on 2023-04-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
